### PR TITLE
Added Job website

### PR DESCRIPTION
**Pull request by apu52**
Hello Sir,
I have added the job finding website
Please take a look at my PR & please merge it under OSEN.

### CODE REVIEW

**Comment by apu52** [comment]
@Shu12388y Please take a review of my PR & please merge it under OSEN

**Comment by Shu12388y** [comment]
@apu52 there is a conflict please resolve it

**Comment by apu52** [comment]
> @apu52 there is a conflict please resolve it
@Shu12388y  I have made the changes ...Please review the PR & please merge it under OSEN

**Comment by Shu12388y** [comment]
@apu52 there is conflict resolve it

**Comment by apu52** [comment]
> @apu52 there is conflict resolve it

@Shu12388y I have resolved the changes

**Comment by shruti-sen2004** [comment]
@Shu12388y to let you know this project is actually developed by 4 people in total. Thus I consider submitting it as a stand-alone project would be unfair. Thus if possible please revert the merge or remove the project from your repository.

Thanking you,
Shruti Sen

**Pull request merged**
