### PR TITLE
Added Food website

### PR DESCRIPTION
**Pull request by apu52**
Hello Sir,
I have added my Food website
Please take a review of my PR & please merge it under OSEN

### CODE REVIEW

**Comment by apu52** [comment]
@Shu12388y Please take a review of my PR & please merge it under OSEN

**Review by Shu12388y — CHANGES_REQUESTED** [review]
move the author below the screenshot

**Comment by apu52** [comment]
> move the author below the screenshot

@Shu12388y I have made the changes. Please merge my PR.

**Comment by apu52** [comment]
@Shu12388y Can you please add SIMPLE/MEDIUM/HARD tag as per your review with the PR , otherwise the PR will not be counted in OSEN

**Pull request merged**
